In [137]:
import yfinance as yf
from yahoofinancials import YahooFinancials
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

In [140]:
# Specify stock ticker
ticker = 'AAPL'

# Need to call after specifying stock ticker for pulling financial statements from yahoofinancials 
yahoo_financials = YahooFinancials(ticker)

In [154]:
# Obtain income statements
income = yahoo_financials.get_financial_stmts('annual', 'income')
income_one = pd.DataFrame(income['incomeStatementHistory'][ticker][0])
income_two = pd.DataFrame(income['incomeStatementHistory'][ticker][1])
income_three = pd.DataFrame(income['incomeStatementHistory'][ticker][2])
income_four = pd.DataFrame(income['incomeStatementHistory'][ticker][3])
income_combined = pd.concat([income_one,income_two,income_three,income_four], axis=1).astype('float')
pd.options.display.float_format = "{:,.2f}".format
income_combined

,2020-09-26,2019-09-28,2018-09-29,2017-09-30
costOfRevenue,"169,559,000,000.00","161,782,000,000.00","163,756,000,000.00","141,048,000,000.00"
discontinuedOperations,nan,nan,nan,nan
ebit,"66,288,000,000.00","63,930,000,000.00","70,898,000,000.00","61,344,000,000.00"
effectOfAccountingCharges,nan,nan,nan,nan
extraordinaryItems,nan,nan,nan,nan
grossProfit,"104,956,000,000.00","98,392,000,000.00","101,839,000,000.00","88,186,000,000.00"
incomeBeforeTax,"67,091,000,000.00","65,737,000,000.00","72,903,000,000.00","64,089,000,000.00"
incomeTaxExpense,"9,680,000,000.00","10,481,000,000.00","13,372,000,000.00","15,738,000,000.00"
interestExpense,"-2,873,000,000.00","-3,576,000,000.00","-3,240,000,000.00","-2,323,000,000.00"
minorityInterest,nan,nan,nan,nan
netIncome,"57,411,000,000.00","55,256,000,000.00","59,531,000,000.00","48,351,000,000.00"
netIncomeApplicableToCommonShares,"57,411,000,000.00","55,256,000,000.00","59,531,000,000.00","48,351,000,000.00"
netIncomeFromContinuingOps,"57,411,000,000.00","55,256,000,000.00","59,531,000,000.00","48,351,000,000.00"
nonRecurring,nan,nan,nan,nan
operatingIncome,"66,288,000,000.00","63,930,000,000.00","70,898,000,000.00","61,344,000,000.00"
otherItems,nan,nan,nan,nan
otherOperatingExpenses,nan,nan,nan,nan
researchDevelopment,"18,752,000,000.00","16,217,000,000.00","14,236,000,000.00","11,581,000,000.00"
sellingGeneralAdministrative,"19,916,000,000.00","18,245,000,000.00","16,705,000,000.00","15,261,000,000.00"
totalOperatingExpenses,"208,227,000,000.00","196,244,000,000.00","194,697,000,000.00","167,890,000,000.00"
totalOtherIncomeExpenseNet,"803,000,000.00","1,807,000,000.00","2,005,000,000.00","2,745,000,000.00"
totalRevenue,"274,515,000,000.00","260,174,000,000.00","265,595,000,000.00","229,234,000,000.00"

In [152]:
# Obtain balance sheet
balance = yahoo_financials.get_financial_stmts('annual', 'balance')
balance_one = pd.DataFrame(balance['balanceSheetHistory'][ticker][0])
balance_two = pd.DataFrame(balance['balanceSheetHistory'][ticker][1])
balance_three = pd.DataFrame(balance['balanceSheetHistory'][ticker][2])
balance_four = pd.DataFrame(balance['balanceSheetHistory'][ticker][3])
balance_combined = pd.concat([balance_one,balance_two,balance_three,balance_four], axis=1).astype('float')
pd.options.display.float_format = "{:,.2f}".format
balance_combined

,2020-09-26,2019-09-28,2018-09-29,2017-09-30
accountsPayable,"42,296,000,000.00","46,236,000,000.00","55,888,000,000.00","44,242,000,000.00"
cash,"38,016,000,000.00","48,844,000,000.00","25,913,000,000.00","20,289,000,000.00"
commonStock,"50,779,000,000.00","45,174,000,000.00","40,201,000,000.00","35,867,000,000.00"
inventory,"4,061,000,000.00","4,106,000,000.00","3,956,000,000.00","4,855,000,000.00"
longTermDebt,"98,667,000,000.00","91,807,000,000.00","93,735,000,000.00","97,207,000,000.00"
longTermInvestments,"100,887,000,000.00","105,341,000,000.00","170,799,000,000.00","194,714,000,000.00"
netReceivables,"37,445,000,000.00","45,804,000,000.00","48,995,000,000.00","35,673,000,000.00"
netTangibleAssets,"65,339,000,000.00","90,488,000,000.00","107,147,000,000.00","134,047,000,000.00"
otherAssets,"33,952,000,000.00","32,978,000,000.00","22,283,000,000.00","18,177,000,000.00"
otherCurrentAssets,"11,264,000,000.00","12,352,000,000.00","12,087,000,000.00","13,936,000,000.00"
otherCurrentLiab,"47,867,000,000.00","43,242,000,000.00","39,293,000,000.00","38,099,000,000.00"
otherLiab,"46,108,000,000.00","50,503,000,000.00","48,914,000,000.00","43,251,000,000.00"
otherStockholderEquity,"-406,000,000.00","-584,000,000.00","-3,454,000,000.00","-150,000,000.00"
propertyPlantEquipment,"45,336,000,000.00","37,378,000,000.00","41,304,000,000.00","33,783,000,000.00"
retainedEarnings,"14,966,000,000.00","45,898,000,000.00","70,400,000,000.00","98,330,000,000.00"
shortLongTermDebt,"8,773,000,000.00","10,260,000,000.00","8,784,000,000.00","6,496,000,000.00"
shortTermInvestments,"52,927,000,000.00","51,713,000,000.00","40,388,000,000.00","53,892,000,000.00"
totalAssets,"323,888,000,000.00","338,516,000,000.00","365,725,000,000.00","375,319,000,000.00"
totalCurrentAssets,"143,713,000,000.00","162,819,000,000.00","131,339,000,000.00","128,645,000,000.00"
totalCurrentLiabilities,"105,392,000,000.00","105,718,000,000.00","115,929,000,000.00","100,814,000,000.00"
totalLiab,"258,549,000,000.00","248,028,000,000.00","258,578,000,000.00","241,272,000,000.00"
totalStockholderEquity,"65,339,000,000.00","90,488,000,000.00","107,147,000,000.00","134,047,000,000.00"
treasuryStock,"-406,000,000.00","-584,000,000.00","-3,454,000,000.00","-150,000,000.00"

In [153]:
# Obtain annual cash-flow statements
cash = yahoo_financials.get_financial_stmts('annual', 'cash')
cash_one = pd.DataFrame(cash['cashflowStatementHistory'][ticker][0])
cash_two = pd.DataFrame(cash['cashflowStatementHistory'][ticker][1])
cash_three = pd.DataFrame(cash['cashflowStatementHistory'][ticker][2])
cash_four = pd.DataFrame(cash['cashflowStatementHistory'][ticker][3])
cash_combined = pd.concat([cash_one,cash_two,cash_three,cash_four], axis=1).astype('float')
pd.options.display.float_format = "{:,.2f}".format
cash_combined

,2020-09-26,2019-09-28,2018-09-29,2017-09-30
capitalExpenditures,"-7,309,000,000.00","-10,495,000,000.00","-13,313,000,000.00","-12,451,000,000.00"
changeInCash,"-10,435,000,000.00","24,311,000,000.00","5,624,000,000.00","-195,000,000.00"
changeToAccountReceivables,"6,917,000,000.00","245,000,000.00","-5,322,000,000.00","-2,093,000,000.00"
changeToInventory,"-127,000,000.00","-289,000,000.00","828,000,000.00","-2,723,000,000.00"
changeToLiabilities,"-1,981,000,000.00","-2,548,000,000.00","9,172,000,000.00","8,373,000,000.00"
changeToNetincome,"6,517,000,000.00","5,076,000,000.00","-27,694,000,000.00","10,640,000,000.00"
changeToOperatingActivities,"881,000,000.00","-896,000,000.00","30,016,000,000.00","-8,480,000,000.00"
depreciation,"11,056,000,000.00","12,547,000,000.00","10,903,000,000.00","10,157,000,000.00"
dividendsPaid,"-14,081,000,000.00","-14,119,000,000.00","-13,712,000,000.00","-12,769,000,000.00"
investments,"5,335,000,000.00","58,093,000,000.00","30,845,000,000.00","-33,542,000,000.00"
issuanceOfStock,"880,000,000.00","781,000,000.00","669,000,000.00","555,000,000.00"
netBorrowings,"2,499,000,000.00","-7,819,000,000.00","432,000,000.00","29,014,000,000.00"
netIncome,"57,411,000,000.00","55,256,000,000.00","59,531,000,000.00","48,351,000,000.00"
otherCashflowsFromFinancingActivities,"-126,000,000.00","-105,000,000.00","-105,000,000.00","-105,000,000.00"
otherCashflowsFromInvestingActivities,"-791,000,000.00","-1,078,000,000.00","-745,000,000.00","-124,000,000.00"
repurchaseOfStock,"-75,992,000,000.00","-69,714,000,000.00","-75,265,000,000.00","-34,774,000,000.00"
totalCashFromFinancingActivities,"-86,820,000,000.00","-90,976,000,000.00","-87,876,000,000.00","-17,974,000,000.00"
totalCashFromOperatingActivities,"80,674,000,000.00","69,391,000,000.00","77,434,000,000.00","64,225,000,000.00"
totalCashflowsFromInvestingActivities,"-4,289,000,000.00","45,896,000,000.00","16,066,000,000.00","-46,446,000,000.00"